services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.13.1-management
    ports:
      - '5672:5672'
      - '15672:15672'

networks:
  mynet:
    driver: bridge